// ...existing code...
const theme = {
    // ...existing code...
    typography: {
        // ...existing code...
        fontFamily: {
            heading: "'Lato', sans-serif",
            // ...existing code...
        },
        // ...existing code...
    },
    // ...existing code...
}
// ...existing code...
